import type { Metadata } from 'next'
import './globals.css'
import styles from './layout.module.css'

import StyledComponentsRegistry from '../lib/AntdRegistry'

export const metadata: Metadata = {
  title: 'Next js 14, PRETZ',
  description: 'Generated by doremi',
}
const RootLayout = async ({ children }: React.PropsWithChildren) => (
  <html>
    <body className={styles.layout__body}>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
    </body>
  </html>
)
export default RootLayout
